messages:
  chatformat: '%player% &8»&r %msg%'
  info:
    noPermission: '&8[&6Basic&8] &cDu hast keine Rechte dafür!'
    noConsoleCommand: '&8[&6Basic&8] &cDieser Befehl geht nur im Spiel!'
  commands:
    basic:
      configReload: '&8[&6Basic&8] &aDie Plugin Config wurde erneut geladen.'
    gamemode:
      usage: '&8[&6Basic&8] &aVerwende /gamemode [survival/creative/adventure/spectator].'
      survival:
        self: '&8[&6Basic&8] &aDein Gamemode wurde auf Survival gesetzt.'
        other: '&8[&6Basic&8] &aDu hast den Gamemode des Spielers auf Survival gesetzt.'
      creative:
        self: '&8[&6Basic&8] &aDein Gamemode wurde auf Creative gesetzt.'
        other: '&8[&6Basic&8] &aDu hast den Gamemode des Spielers auf Creative gesetzt.'
      adventure:
        self: '&8[&6Basic&8] &aDein Gamemode wurde auf Adventure gesetzt.'
        other: '&8[&6Basic&8] &aDu hast den Gamemode des Spielers auf Adventure gesetzt.'
      spectator:
        self: '&8[&6Basic&8] &aDein Gamemode wurde auf Spectator gesetzt.'
        other: '&8[&6Basic&8] &aDu hast den Gamemode des Spielers auf Spectator gesetzt.'
      noGamemode: '&8[&6Basic&8] &cKein Gamemode ausgewählt.'
      noTarget: '&8[&6Basic&8] &cDer Spieler ist nicht online.'
    clearinventory:
      noTarget: '&8[&6Basic&8] &cDer Spieler ist nicht online.'
      self: '&8[&6Basic&8] &aDein Inventar wurde geleert.'
      other: '&8[&6Basic&8] &aDu hast das Inventar des Spielers geleert.'
    feed:
      noTarget: '&8[&6Basic&8] &cDer Spieler ist nicht online.'
      self: '&8[&6Basic&8] &aDu wurdest gesättigt.'
      other: '&8[&6Basic&8] &aDu hast den Spieler gesättigt.'
    fly:
      noTarget: '&8[&6Basic&8] &cDer Spieler ist nicht online.'
      self:
        'on': '&8[&6Basic&8] &aDein Flugmodus wurde auf aktiviert gesetzt.'
        'off': '&8[&6Basic&8] &aDein Flugmodus wurde auf deaktiviert gesetzt.'
      other:
        'on': '&8[&6Basic&8] &aDu hast den Flugmodus des Spielers auf aktiviert gesetzt.'
        'off': '&8[&6Basic&8] &aDu hast den Flugmodus des Spielers auf deaktiviert
          gesetzt.'
    god:
      noTarget: '&8[&6Basic&8] &cDer Spieler ist nicht online.'
      self:
        'on': '&8[&6Basic&8] &aDu bist nun im Gottmodus!'
        'off': '&8[&6Basic&8] &aDu bist nun nicht mehr im Gottmodus!'
    heal:
      noTarget: '&8[&6Basic&8] &cDer Spieler ist nicht online.'
      self: '&8[&6Basic&8] &aDu wurdest geheilt.'
      other: '&8[&6Basic&8] &aDu hast den Spieler geheilt.'
    repair:
      noTarget: '&8[&6Basic&8] &cDer Spieler ist nicht online.'
      self:
        noItem: '&8[&6Basic&8] &aDu hast kein Item in deiner Hand.'
        repaired: '&8[&6Basic&8] &aDas Item in deiner Hand wurde repariert.'
        repairedAll: '&8[&6Basic&8] &aAlle Items in deinem Inventar wurden repariert.'
    workbench:
      noTarget: '&8[&6Basic&8] &cDer Spieler ist nicht online.'
      other: '&8[&6Basic&8] &aDu hast dem Spieler eine Werkbank geöffnet.'
      self: '&8[&6Basic&8] &aDir wurde eine Werkbank geöffnet.'
    spawn:
      noTarget: '&8[&6Basic&8] &cDer Spieler ist nicht online.'
      noSpawnPoint: '&8[&6Basic&8] &aEs existiert kein Spawn.'
      teleported:
        self: '&8[&6Basic&8] &aDu wurdest zum Spawn teleportiert.'
        other: '&8[&6Basic&8] &aDu hast den Spieler zum Spawn teleportiert.'
      setspawn:
        set:
          yourLocation: '&8[&6Basic&8] &aDer Spawn wurde auf deine Position gesetzt.'
      delspawn: '&8[&6Basic&8] &aDer Spawn wurde erfolgreich gelöscht.'
  playerJoin: '&8[&a+&8]&r %player_name%'
  playerQuit: '&8[&c-&8]&r %player_name%'